/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],

  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Stared',
      items: ['tutorials', 'playground'],
      link: {
        type: 'doc',
        id: 'tutorials',
      },
      collapsed: false,
      collapsible: false,
    },
    {
      type: 'link',
      label: 'Guides',
      href: '/docs/guides',
    },
    // In order to generate the API directory, we must manually add the sidebar below.
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'doc',
        id: 'api-reference/api-reference',
      },
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'Global API',
          items: ['api-reference/application', 'api-reference/general'],
        },
        {
          type: 'category',
          label: 'Composition API',
          items: ['api-reference/setup', 'api-reference/lifecycle-hook'],
        },
      ],
    },
    {
      type: 'link',
      label: 'Guides',
      href: '/docs/guides',
    },
    // {
    //   "Getting Stared": ["tutorials", "playground"]
    // },
    // {
    //   "Guides"
    // }
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
